apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Même capacité que le PV pour correspondre
