apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-data-volume
spec:
  accessModes:
    - ReadWriteMany  # Permet à plusieurs conteneurs d'écrire/lire sur ce volume
  capacity:
    storage: 1Gi  # Taille du volume
  hostPath:
    path: /mnt/data  # Chemin local sur le cluster
