apiVersion: v1
kind: Service
metadata:
  name: api-service  # Nom du service
spec:
  selector:
    app: api-app  # Associe les pods ayant ce label
  ports:
    - protocol: TCP
      port: 80  # Port d’accès pour le service
      targetPort: 8000  # Le port exposé par FastAPI dans le conteneur
  type: LoadBalancer  # LoadBalancer pour le cloud
