# Étape 1 : Choisir l'image de base avec Python
FROM python:3.13.0

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier le fichier requirements.txt et installer les dépendances
COPY src/api/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Étape 4 : Copier le code FastAPI dans le conteneur
COPY src/api /app

# Étape 5 : Exposer le port de l'API
EXPOSE 8000

# Étape 6 : Spécifier la commande de démarrage
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
